POST http://localhost:8000/register HTTP/1.1
content-type: application/json

{
    "username": "john",
    "password": "1234",
    "usertype": "student"
}

###
POST http://localhost:8000/login HTTP/1.1
content-type: application/json

{
    "username": "john",
    "password": "1234"
}

###

POST http://localhost:8000/login HTTP/1.1
content-type: application/json

{
    "username": "notyash",
    "password": "123"
}

###


GET http://localhost:8000/student/info HTTP/1.1
Authorization: Bearer token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJ1c2VydHlwZSI6InN0dWRlbnQiLCJleHAiOjE3MDgwMDc1MTYsImlzcyI6ImF0dGVuZGFuY2UtYXBpLWdvIn0.kCC1gDPe8a8RWjpI0Sm4c5Zwtg2VaDX27A_Sv57PxUQ



